{"uuid": "599000cd-0728-4c3d-ad6a-ff11aeef3fa2", "children": ["515905d7-0737-47c9-bbbf-1e78de430f07", "1e1a208f-07d6-4b56-8071-678d65393882", "873e6cbf-075c-424f-a556-d501d935bdb3", "d4a5ba4b-b6b5-477c-9bbd-562dec53f720"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"D:\\Anaconda36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda36\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda36\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\Git_Project\\web_auto\\case\\conftest.py\", line 13, in driver\n    _driver = webdriver.Chrome()\n  File \"D:\\Anaconda36\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 62, in __init__\n    self.service.start()\n  File \"D:\\Anaconda36\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 71, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1593699554158, "stop": 1593699554177}], "start": 1593699554158, "stop": 1593699555026}